# Generated by Django 5.2.7 on 2025-10-16 16:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerID', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=100)),
                ('ContactNumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('CardID', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('CardType', models.CharField(max_length=50)),
                ('CreditLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreditBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MinimumPaymentDue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentDueDate', models.DateTimeField()),
                ('LastPaymentDate', models.DateTimeField(blank=True, null=True)),
                ('RewardsPoints', models.IntegerField()),
                ('CustomerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='kog_app.customers')),
            ],
            options={
                'db_table': 'credit_cards',
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountType', models.CharField(max_length=50)),
                ('AccountBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DateOfOpening', models.DateTimeField(auto_now_add=True)),
                ('LastTransactionDate', models.DateTimeField(auto_now=True)),
                ('BranchID', models.CharField(max_length=50)),
                ('CustomerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='kog_app.customers')),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['-DateOfOpening'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('FeedbackID', models.AutoField(primary_key=True, serialize=False)),
                ('FeedbackDate', models.DateTimeField(auto_now_add=True)),
                ('FeedbackType', models.CharField(max_length=50)),
                ('ResolutionStatus', models.CharField(max_length=50)),
                ('ResolutionDate', models.DateTimeField(blank=True, null=True)),
                ('CustomerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='kog_app.customers')),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('LoanID', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('LoanType', models.CharField(max_length=50)),
                ('LoanAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('InterestRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('LoanTerm', models.IntegerField()),
                ('ApprovalDate', models.DateTimeField(auto_now_add=True)),
                ('LoanStatus', models.CharField(max_length=50)),
                ('CustomerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='kog_app.customers')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('TransactionID', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('TransactionDate', models.DateTimeField(auto_now_add=True)),
                ('TransactionType', models.CharField(max_length=50)),
                ('TransactionAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BalanceAfterTransaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Anomaly', models.BooleanField(default=False)),
                ('AccountID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='kog_app.accounts')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-TransactionDate'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'db_table': 'user_role',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='kog_app.userrole'),
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='kog_app.userrole')),
            ],
            options={
                'db_table': 'admins',
            },
        ),
    ]
